flybits/actions

.github/workflows/go-cover.yml, go-cover/README.md, go-cover/action.yml, go-cover/entrypoint.sh
=> Improve go-cover action

.github/workflows/go-grpc.yml, go-grpc/Dockerfile, go-grpc/README.md, go-grpc/action.yml, go-grpc/entrypoint.sh, go-grpc/test/hello.proto
=> Add go-grpc action

semver/entrypoint.sh
=> Update semver action

.github/workflows/go-grpc.yml, go-cover/Dockerfile, go-grpc/Dockerfile, go-lint/Dockerfile
=> Revert "Update golang Docker tag to v1.17"

deployment/README.md, deployment/action.yml
=> Regex: Validate version file format

deployment/README.md, deployment/action.yml
=> Fix: Set the user information who trigger the workflow

deployment/action.yml
=> Only main branch

deployment/action.yml
=> Fix: username

go-vulncheck/action.yml
Creating a standard job for govulncheck in order to standardize the process of performing nightly and pipeline govulnchecks
=> Add Generalized Action for Govulncheck

go-vulncheck/action.yml
=> Govulncheckv1

go-vulncheck/action.yml
=> [PET-1275] bumb go-vulncheck action to 1.22.2

scan-frontend/action.yml
=> Add frontend scanning for Actions

backend/build/action.yaml
The Build step was always creating a .dev docker image. I have added logic to fix this
=> [PET-000] Fixed issue with staging not generating the correct docker image

backend/build/action.yaml, backend/push/action.yaml
One of the problems we ran into is that the between the build and push docker step a new commit occurred and it through the whole process off, so we need to pass the version from the build step to the push step
=> [PET-000] There was a disconnect when code was deployed between Build/Push steps

deployment/action.yml
=> Revert "Feature/release issue"

backend/build/action.yaml
Need to be able to resolve the issue where some repositories have multiple images that are created such as:
https://github.com/flybits/auth/pull/896
=> [PET-000] Added Option for changing the dockerfile in case there are multiple

deploy-android-app/action.yml
=> [PET-000] Add new inputs to make this a generic deployment

backend/push/action.yaml
Here are screenshots the show that the dev image got updated on both GCP Core Dev and AWS Development
GCP Core Dev:
AWS Development
=> Add Core Dev GCP to deployment

backend/build/action.yaml
=> get rid of trivy

.github/CODEOWNERS
=> [BET-000] Update CODEOWNERS

backend/go-vulncheck/action.yml
=> [PET-000] update golang version to go1.24

backend/push/action.yaml
=> Retry Backend Push command for a max 4 times 

backend/push/action.yaml
=> Revert "Retry Backend Push command for a max 4 times "

.github/CODEOWNERS, mobile/ios-deploy-app/action.yaml
=> Fix indentation

backend/push/action.yaml
=> adjust actions for replacing dev-gcp for core-dev

backend/clean-docker/action.yaml
We recently noticed backend services were failing their nightly tasks because the docker cleanup task was not finishing. Upon investigation I noticed that https://index.docker.io/v1/ is now returning a 404. So I decided to re-write the login process to make it a bit more simple and easy to follow.
=> [PET-000] Fix Auth Schema Link

backend/clean-docker/action.yaml, backend/push/action.yaml
I found a few cases (thanks @arman-masoumi ) where push and deployment steps were failing. As per:
Deployment Failure: https://github.com/flybits/rules/actions/runs/16325047026/job/46112811508
Push Failure: https://github.com/flybits/location/actions/runs/16324515695/job/46111148316
I have tested these on Labels repo and it appears to work but its hard to reproduce this issue. It was one of those random issues that just resolves itself.
=> [PET-000] Fixing issues
